version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - cd infra/terraform
      - terraform init
      - terraform workspace select $ENVIRONMENT || terraform workspace new $ENVIRONMENT

  build:
    commands:
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo "Infrastructure deployed successfully"
      - terraform output -json > outputs.json

artifacts:
  files:
    - infra/terraform/outputs.json
